config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update,]
  get "/home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  def get_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have create book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path

  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to '/users'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @book = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
<%= image_tag user.get_image, size:"63x63" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </th>
    </tr>
  </tbody>
</table>

<h2 class="mt-3">New book</h2>
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<html>
  <head></head>
  <body>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md--8 col-ig-5 px-5 px-sm-0 mx-auto">
            <% if @book.errors.any? %>
              <%= @book.errors.count %>errors prohibited this obj from being saved:
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
              <% end %>
  		      <h1>Editing Book</h1>
  		      <%= form_with model: @book do |f| %>
  		        <div>
  		          <h4>Title</h4>
  		          <%= f.text_field :title %>
  		        </div>
  		        <div>
  		          <h4>Opinion</h4>
  		          <%= f.text_area :body %>
  		        </div>
  		        <div>
  		          <%= f.submit 'Update Book' %>
  		        </div>
  		      <% end %>
  		      <%= link_to "Show", book_path %>

  		      <%= link_to "Back", books_path %>
  		    </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/books/index.html.erb
<html>
  <head></head>
  <body>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <div class="container px-5 px-sm-0">
        <div>
          <% if @book.errors.any? %>
            <%= @book.errors.count %>errors prohibited this obj from being saved:
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-3">
            <!--user info部分-->
            <%= render 'list', book: @book, user: current_user %>
          </div>
          <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
    		              <%= image_tag @user.get_image, size:"40x40" %>
    		            <% end %>
                  </td>
                  <td>
                    <%= link_to book.title, book_path(book.id) %>
                  </td>
                  <td>
                    <%= book.body %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<html>
  <head></head>
  <body>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <div class="container">
        <div>
          <% if @book.errors.any? %>
            <%= @book.errors.count %>errors prohibited this obj from being saved:
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-3">
            <%= render 'books/list', book: @book, user: @user %>
          </div>
          <div class="col-md-8 offset-md-1">
  		      <h2>Book detail</h2>
  		      <table class="table">
  		        <tbody>
  		          <tr>
  		            <td>
  		              <%= link_to user_path(@user.id) do %>
  		                <%= image_tag @user.get_image, size:"40x40" %><br>
  		                <%= @user.name %>
  		              <% end %>
  		            </td>
  		            <td><%= link_to @book.title, book_path(@book.id) %></td>
  		            <td><%= @book.body %></td>
  		            <% if @book.user == current_user %>
  		              <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
  		              <td><%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
  		            <% end %>
  		          </tr>
  		        </tbody>
  		      </table>
  		    </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/homes/about.html.erb
<html>
  <head></head>
  <body>
    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/homes/top.html.erb
<html>
  <head></head>
  <body>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
            <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
            <p>you can share and exchange  your opinions , inpressions , and emotions</p>
            <p> about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <%= link_to "Log in", new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3"%>
              </div>
              <div class="row">
                <%= link_to "Sign up", new_user_registration_path,class: "btn btn-success btn-sm btn-block"%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/7734cd77ed.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

    <header>
      <nav class="navbar nav-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div class="navbar-brand"><%= link_to "Bookers", root_path %></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-home"></i>Home
              <% end %>
              <%= link_to users_path do %>
                <i class="fas fa-users"></i>Users
              <% end %>
              <%= link_to books_path do %>
                <i class="fas fa-book-open"></i>Books
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>Log out
              <% end %>
            <% else %>
              <%= link_to root_path do %>
                <i class="fas fa-home"></i>Home
              <% end %>
              <%= link_to about_path do %>
                <i class="fas fa-link"></i>About
              <% end %>
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus"></i>Sign up
              <% end %>
              <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt"></i>Log in
              <% end %>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<html>
  <head></head>
  <body>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>User info</h2>
            <div>
              <% if @user.errors.any? %>
              <%= @user.errors.count %>errors prohibited this obj from being saved:
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
              <% end %>
            </div>
            <%= form_with model: @user do |f| %>
              <div>
                <h4>Name</h4>
                <%= f.text_field :name %>
              </div>
              <div>
                <h4>Image</h4>
                <%= f.file_field :profile_image, accept: "image/*" %>
              </div>
              <div>
                <h4>Introduction</h4>
                <%= f.text_area :introduction %>
              </div>
              <div>
                <%= f.submit 'Update User' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<html>
  <head></head>
  <body>
    <main>
      <p id="notice"></p>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-3">
            <%= render 'books/list', book: @book, user: current_user %>
          </div>
          <div class="col-md-8 offset-md-1">
  		      <h2>Users</h2>
  		      <table class="table">
  		        <thead>
  		          <tr>
                  <th>image</th>
                  <th>name</th>
                  <th colspan="3"></th>
                </tr>
  		        </thead>
  		        <tbody>
                <% @users.each do |user| %>
                  <tr>
  		              <td><%= image_tag user.get_image, size:"40x40" %></td>
  		              <td><%= user.name %></td>
  		              <td><%= link_to "Show", user_path(user.id) %></td>
  		            </tr>
  		          <% end %>
  		        </tbody>
  		      </table>
  		    </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<html>
  <head></head>
  <body>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <%= render 'books/list', book: @book, user: @user %>
          </div>
          <div class="col-md-8 offset-md-1">
  		      <h2>Books</h2>
  		      <table class="table">
  		        <thead>
  		          <tr>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
  		        </thead>
  		        <tbody>
  		          <% @book.each do |book| %>
  		            <tr>
    		            <td>
    		              <%= link_to user_path(book.user) do %>
    		                <%= image_tag @user.get_image, size:"40x40" %>
    		              <% end %>
    		            </td>
    		            <td><%= link_to book.title, book_path(book.id) %></td>
    		            <td><%= book.body %></td>
    		          </tr>
  		          <% end %>
  		          </tr>
  		        </tbody>
  		      </table>
  		    </div>
        </div>
      </div>
    </main>
  </body>
</html>